```{r}
rm(list = ls())
library(ROCR)
library(pROC)
basecol <- function(n) {
  colall <- c('#d7191c', '#31a354', '#756bb1', '#0571b0', '#d95f0e', '#bdbdbd')
  return(colall[1:n])
}

mytemp<-theme(panel.background=element_rect(fill="white",colour=NA), 
              panel.grid.major =element_blank(),
              panel.grid.minor = element_blank(),
              axis.line = element_line(colour = "black",linewidth=0.5),
              axis.text.x = element_text(colour = "black"),
              axis.text.y =element_text(colour = "black"),
              axis.title.y=element_text(colour = "black"))

train_all <- read_tsv("pathto/paper/train_sample_score_all.txt")
train_psa420 <- train_all %>% dplyr::filter(PSA > 4 & PSA < 20)
########################################################################
#pred_cnv <- prediction(train_all[,2],train_all[,6])
#perf_cnv <- performance(pred_cnv,"tpr","fpr")
#table_train <- data.frame(FDR=as.numeric(perf@x.values[[1]]),TPR)

#pred <- prediction(p_tab3[,5],c(rep(0,10),rep(1,13)))
#perf <- performance(pred,"tpr","fpr")  
#p_tmp2 <- data.frame(FPR=as.numeric(perf@x.values[[1]]),TPR=as.numeric(perf@y.values[[1]]),marker=paste("AUC: 95%CI",round(roc_ci[2],3),"(",round(roc_ci[1],3),"-",round(roc_ci[3],3),")",sep=""))


roc_cnv <- pROC::roc(label~cnv_score,train_all,ci = TRUE)
roc_fsc <- pROC::roc(label~fsc_score,train_all,ci = TRUE) 
roc_fsd <- pROC::roc(label~fsd_score,train_all,ci = TRUE)

roc_cnv_psa420_train <- pROC::roc(label~cnv_score,train_psa420,ci = TRUE)
roc_fsc_psa420_train <- pROC::roc(label~fsc_score,train_psa420,ci = TRUE)
roc_fsd_psa420_train <- pROC::roc(label~fsd_score,train_psa420,ci = TRUE)
#train_cnv
youden_index_cnv <- roc_cnv$sensitivities + roc_cnv$specificities - 1
best_cnv <- roc_cnv$thresholds[which.max(youden_index_cnv)]
ci_values_cnv <- ci.thresholds(roc_cnv,thresholds = best_cnv)
sens_cnv <- ci_values_cnv$sensitivity
spec_cnv <- ci_values_cnv$specificity
#train_fsc
youden_index_fsc <- roc_fsc$sensitivities + roc_fsc$specificities -1
best_fsc <- roc_fsc$thresholds[which.max(youden_index_fsc)]
ci_values_fsc <- ci.thresholds(roc_fsc,thresholds = best_fsc)
sens_fsc <- ci_values_fsc$sensitivity
spec_fsc <- ci_values_fsc$specificity
#train_fsd
youden_index_fsd <- roc_fsd$sensitivities + roc_fsd$specificities -1
best_fsd <- roc_fsd$thresholds[which.max(youden_index_fsd)]
ci_values_fsd <- ci.thresholds(roc_fsd,thresholds = best_fsd)
sens_fsd <- ci_values_fsd$sensitivity
spec_fsd <- ci_values_fsd$specificity

#train_cnv_psa420
youden_index_cnv_psa420 <- roc_cnv_psa420_train$sensitivities + roc_cnv_psa420_train$specificities -1
best_cnv_psa420 <- roc_cnv_psa420_train$thresholds[which.max(youden_index_cnv_psa420)]
ci_values_cnv_psa420 <- ci.thresholds(roc_cnv_psa420_train,thresholds = best_cnv_psa420)

#train_fsc_psa420
youden_index_fsc_psa420 <- roc_fsc_psa420_train$sensitivities + roc_fsc_psa420_train$specificities -1
best_fsc_psa420 <- roc_fsc_psa420_train$thresholds[which.max(youden_index_fsc_psa420)]
ci_values_fsc_psa420 <- ci.thresholds(roc_fsc_psa420_train,thresholds = best_fsc_psa420)

#train_fsd_psa420
youden_index_fsd_psa420 <- roc_fsd_psa420_train$sensitivities + roc_fsd_psa420_train$specificities -1
best_fsd_psa420 <- roc_fsd_psa420_train$thresholds[which.max(youden_index_fsd_psa420)]
ci_values_fsd_psa420 <- ci.thresholds(roc_fsd_psa420_train,thresholds = best_fsd_psa420)

#train_fig2-3
table <- data.frame(
  sample = c("cnv","cnv","fsc","fsc","fsd","fsd","cvn_psa420","cnv_psa420","fsc_psa420","fsc_psa420","fsd_psa420","fsd_psa420"),
  group = c("sens","spec","sens","spec","sens","spec","sens","spec","sens","spec","sens","spec"),
  value = c(ci_values_cnv$sensitivity[[2]],ci_values_cnv$specificity[[2]],ci_values_fsc$sensitivity[[2]],ci_values_fsc$specificity[[2]],ci_values_fsd$sensitivity[[2]],ci_values_fsd$specificity[[2]],ci_values_cnv_psa420$sensitivity[[2]],ci_values_cnv_psa420$specificity[[2]],ci_values_fsc_psa420$sensitivity[[2]],ci_values_fsc_psa420$specificity[[2]],ci_values_fsd_psa420$sensitivity[[2]],ci_values_fsd_psa420$specificity[[2]]),
  low = c(ci_values_cnv$sensitivity[[1]],ci_values_cnv$specificity[[1]],ci_values_fsc$sensitivity[[1]],ci_values_fsc$specificity[[1]],ci_values_fsd$sensitivity[[1]],ci_values_fsd$specificity[[1]],ci_values_cnv_psa420$sensitivity[[1]],ci_values_cnv_psa420$specificity[[1]],ci_values_fsc_psa420$sensitivity[[1]],ci_values_fsc_psa420$specificity[[1]],ci_values_fsd_psa420$sensitivity[[1]],ci_values_fsd_psa420$specificity[[1]]),
  high = c(ci_values_cnv$sensitivity[[3]],ci_values_cnv$specificity[[3]],ci_values_fsc$sensitivity[[3]],ci_values_fsc$specificity[[3]],ci_values_fsd$sensitivity[[3]],ci_values_fsd$specificity[[3]],ci_values_cnv_psa420$sensitivity[[3]],ci_values_cnv_psa420$specificity[[3]],ci_values_fsc_psa420$sensitivity[[3]],ci_values_fsc_psa420$specificity[[3]],ci_values_fsd_psa420$sensitivity[[3]],ci_values_fsd_psa420$specificity[[3]])
)
table <- table %>% mutate(index = 1:12)

write.table(table,"pathto/paper/table.xls",sep = "\t",quote = F,row.names = F)

###########################
min <- c(table$low)
max <- c(table$high)

fig2_3 <- ggplot(table,aes(x = index,y = value,color = group)) +
  geom_point(data = table,aes(x = index,y = value,color = group),size = 3) +
  geom_segment(x = c(1,2,3,4,5,6,7,8,9,10,11,12),xend = c(1,2,3,4,5,6,7,8,9,10,11,12),y = min,yend =  max,size = 1) +
  mytemp +
  geom_vline(xintercept = c(2.5,4.5,6.5,8.5,10.5),color = "darkgrey",linetype = "dashed") +
  labs(x="",y="",color="") +
  theme(legend.position = c(0.92, 0.2),legend.key.size = unit(25, "points")) +
  theme(axis.ticks.x = element_blank()) +
  scale_x_continuous(breaks = c(1.5,3.5,5.5,7.5,9.5,11.5),labels = c("cnv","fsc","fsd","cnv_psa420","fsc_psa420","fsd_psa420")) +
  scale_y_continuous(limits = c(0.2,1),labels = c("20%","40%", "60%", "80%", "100%"))



################
#fig2_3 <- ggplot() +
#  geom_point(data = table,aes(x = index,y = value,color = group),size = 3) +
#  geom_errorbar(data = table,aes(x = index,ymin = low,ymax = high,color = group),width = 0,size = 1) +
#  mytemp +
#  geom_vline(xintercept = c(2.5,4.5,6.5,8.5,10.5),color = "darkgrey",linetype = "dashed") +
#  labs(x="",y="",color="") +
#  theme(legend.position = c(0.92, 0.2),legend.key.size = unit(30, "points")) +
#  theme(axis.ticks.x = element_blank()) +
#  scale_x_continuous(breaks = c(1.5,3.5,5.5,7.5,9.5,11.5),labels = c("cnv","fsc","fsd","cnv_psa420","fsc_psa420","fsd_psa420")) +
#  scale_y_continuous(limits = c(0.2,1),labels = c("20%","40%", "60%", "80%", "100%"))

ggsave("pathto/paper/fig2_3.pdf",fig2_3,width = 5.8,height = 3.87)
  
  
#test
#q <- plot(roc_cnv,thresholds="best",print.thres="best")

p <- ggroc(list(cnv=roc_cnv,fsc=roc_fsc,fsd=roc_fsd)) +
  labs(color = "AUC: (95% CI)") +
  scale_color_manual(values = c("#d95f0e","#756bb1","#0571b0"),
                     labels = c(paste0("cnv_score, ",round(roc_cnv$auc,3),"(",round(roc_cnv$ci[1],3),
                      "-",round(roc_cnv$ci[3],3),")"),
                      paste0("fsc_score,",round(roc_fsc$auc,3),"(",round(roc_fsc$ci[1],3),
                             "-",round(roc_fsc$ci[3],3),")"),
                      paste0("fsd_score,",round(roc_fsd$auc,3),"(",round(roc_fsd$ci[1],3),
                             "-",round(roc_fsd$ci[3],3),")"))) +
  mytemp +
  theme(legend.position = c(0.65, 0.2))
ggsave("pathto/paper/fig2_1.pdf",p,width = 4.7,height = 4.4)


```

```{r}
test_all <- read.table("pathto/paper/test_sample_score_manual.txt")
roc_cnv_test <- roc(group~cnv,test_all,ci = TRUE)
roc_fsc_test <- roc(group~fsc,test_all,ci = TRUE)
roc_fsd_test <- roc(group~fsd,test_all,ci = TRUE)

p2 <- ggroc(list(cnv=roc_cnv_test,fsc=roc_fsc_test,fsd=roc_fsd_test)) +
  labs(color = "AUC: (95% CI)") +
  scale_color_manual(values = c("#d95f0e","#756bb1","#0571b0"),
                     labels = c(paste0("cnv_score, ",round(roc_cnv_test$auc,3),"(",round(roc_cnv_test$ci[1],3),
                      "-",round(roc_cnv_test$ci[3],3),")"),
                      paste0("fsc_score,",round(roc_fsc_test$auc,3),"(",round(roc_fsc_test$ci[1],3),
                             "-",round(roc_fsc_test$ci[3],3),")"),
                      paste0("fsd_score,",round(roc_fsd_test$auc,3),"(",round(roc_fsd_test$ci[1],3),
                             "-",round(roc_fsd_test$ci[3],3),")"))) +
  mytemp +
  theme(legend.position = c(0.65, 0.2))
ggsave("pathto/paper/fig3_1.pdf",p2,width = 4.7,height = 4.4)
```

```{r}
test_psa420 <- test_all %>% dplyr::filter(PSA >4 & PSA < 20)
roc_cnv_psa420 <- roc(group~cnv,test_psa420,ci = TRUE)
roc_fsc_psa420 <- roc(group~fsc,test_psa420,ci = TRUE)
roc_fsd_psa420 <- roc(group~fsd,test_psa420,ci = TRUE)

#test_cnv
youden_index_cnv_test <- roc_cnv_test$sensitivities + roc_cnv_test$specificities - 1
best_cnv_test <- roc_cnv_test$thresholds[which.max(youden_index_cnv_test)]
ci_values_cnv_test <- ci.thresholds(roc_cnv_test,thresholds = best_cnv_test)
#test_fsc
youden_index_fsc_test <- roc_fsc_test$sensitivities + roc_fsc_test$specificities -1
best_fsc_test <- roc_fsc_test$thresholds[which.max(youden_index_fsc_test)]
ci_values_fsc_test <- ci.thresholds(roc_fsc_test,thresholds = best_fsc_test)
#test_fsd
youden_index_fsd_test <- roc_fsd_test$sensitivities + roc_fsd_test$specificities -1
best_fsd_test <- roc_fsd_test$thresholds[which.max(youden_index_fsd_test)]
ci_values_fsd_test <- ci.thresholds(roc_fsd_test,thresholds = best_fsd_test)
#test_cnv_psa420
youden_index_cnv_psa420_test <- roc_cnv_psa420$sensitivities + roc_cnv_psa420$specificities -1
best_cnv_psa420_test <- roc_cnv_psa420$thresholds[which.max(youden_index_cnv_psa420_test)]
ci_values_cnv_psa420_test <- ci.thresholds(roc_cnv_psa420,thresholds = best_cnv_psa420_test)
#test_fsc_psa420
youden_index_fsc_psa420_test <- roc_fsc_psa420$sensitivities + roc_fsc_psa420$specificities -1
best_fsc_psa420_test <- roc_fsc_psa420$thresholds[which.max(youden_index_fsc_psa420_test)]
ci_values_fsc_psa420_test <- ci.thresholds(roc_fsc_psa420,thresholds = best_fsc_psa420_test)
#test_fsd_psa420
youden_index_fsd_psa420_test <- roc_fsd_psa420$sensitivities + roc_fsd_psa420$specificities -1
best_fsd_psa420_test <- roc_fsd_psa420$thresholds[which.max(youden_index_fsd_psa420_test)]
ci_values_fsd_psa420_test <- ci.thresholds(roc_fsd_psa420,thresholds = best_fsd_psa420_test)

#train_fig3-3
table_test <- data.frame(
  sample = c("cnv","cnv","fsc","fsc","fsd","fsd","cvn_psa420","cnv_psa420","fsc_psa420","fsc_psa420","fsd_psa420","fsd_psa420"),
  group = c("sens","spec","sens","spec","sens","spec","sens","spec","sens","spec","sens","spec"),
  value = c(ci_values_cnv_test$sensitivity[[2]],ci_values_cnv_test$specificity[[2]],ci_values_fsc_test$sensitivity[[2]],ci_values_fsc_test$specificity[[2]],ci_values_fsd_test$sensitivity[[2]],ci_values_fsd_test$specificity[[2]],ci_values_cnv_psa420_test$sensitivity[[2]],ci_values_cnv_psa420_test$specificity[[2]],ci_values_fsc_psa420_test$sensitivity[[2]],ci_values_fsc_psa420_test$specificity[[2]],ci_values_fsd_psa420_test$sensitivity[[2]],ci_values_fsd_psa420_test$specificity[[2]]),
  low = c(ci_values_cnv_test$sensitivity[[1]],ci_values_cnv_test$specificity[[1]],ci_values_fsc_test$sensitivity[[1]],ci_values_fsc_test$specificity[[1]],ci_values_fsd_test$sensitivity[[1]],ci_values_fsd_test$specificity[[1]],ci_values_cnv_psa420_test$sensitivity[[1]],ci_values_cnv_psa420_test$specificity[[1]],ci_values_fsc_psa420_test$sensitivity[[1]],ci_values_fsc_psa420_test$specificity[[1]],ci_values_fsd_psa420_test$sensitivity[[1]],ci_values_fsd_psa420_test$specificity[[1]]),
  high = c(ci_values_cnv_test$sensitivity[[3]],ci_values_cnv_test$specificity[[3]],ci_values_fsc_test$sensitivity[[3]],ci_values_fsc_test$specificity[[3]],ci_values_fsd_test$sensitivity[[3]],ci_values_fsd_test$specificity[[3]],ci_values_cnv_psa420_test$sensitivity[[3]],ci_values_cnv_psa420_test$specificity[[3]],ci_values_fsc_psa420_test$sensitivity[[3]],ci_values_fsc_psa420_test$specificity[[3]],ci_values_fsd_psa420_test$sensitivity[[3]],ci_values_fsd_psa420_test$specificity[[3]])
)
table_test <- table_test %>% mutate(index = 1:12)
  
#test
#q <- plot(roc_cnv,thresholds="best",print.thres="best")

write.table(table_test,"pathto/paper/table_test.xls",sep = "\t",quote = F,row.names = F)

min_test <- c(table_test$low)
max_test <- c(table_test$high)

fig3_3 <- ggplot(table_test,aes(x = index,y = value,color = group)) +
  geom_point(data = table_test,aes(x = index,y = value,color = group),size = 3) +
  geom_segment(x = c(1,2,3,4,5,6,7,8,9,10,11,12),xend = c(1,2,3,4,5,6,7,8,9,10,11,12),y = min_test,yend =  max_test,size = 1) +
  mytemp +
  geom_vline(xintercept = c(2.5,4.5,6.5,8.5,10.5),color = "darkgrey",linetype = "dashed") +
  labs(x="",y="",color="") +
  theme(legend.position = c(0.92, 0.2),legend.key.size = unit(30, "points")) +
  theme(axis.ticks.x = element_blank()) +
  scale_x_continuous(breaks = c(1.5,3.5,5.5,7.5,9.5,11.5),labels = c("cnv","fsc","fsd","cnv_psa420","fsc_psa420","fsd_psa420")) +
  scale_y_continuous(limits = c(0.2,1),labels = c("20%","40%", "60%", "80%", "100%"))


###############################################
#fig3_3 <- ggplot() +
#  geom_point(data = table_test,aes(x = index,y = value,color = group),size = 3) +
#  geom_errorbar(data = table_test,aes(x = index,ymin = low,ymax = high,color = group),width = 0,size = 1) +
#  mytemp +
#  geom_vline(xintercept = c(2.5,4.5,6.5,8.5,10.5),color = "darkgrey",linetype = "dashed") +
#  labs(x="",y="",color="") +
#  theme(legend.position = c(0.92, 0.2),legend.key.size = unit(30, "points")) +
#  theme(axis.ticks.x = element_blank()) +
#  scale_x_continuous(breaks = c(1.5,3.5,5.5,7.5,9.5,11.5),labels = c("cnv","fsc","fsd","cnv_psa420","fsc_psa420","fsd_psa420")) +
#  scale_y_continuous(limits = c(0.2,1),labels = c("20%","40%", "60%", "80%", "100%"))

ggsave("pathto/paper/fig3_3.pdf",fig3_3,width = 5.8,height = 3.87)
  


p3 <- ggroc(list(cnv=roc_cnv_psa420,fsc=roc_fsc_psa420,fsd=roc_fsd_psa420)) +
  labs(color = "AUC: (95% CI)") +
  scale_color_manual(values = c("#d95f0e","#756bb1","#0571b0"),
                     labels = c(paste0("cnv_score, ",round(roc_cnv_psa420$auc,3),"(",round(roc_cnv_psa420$ci[1],3),
                      "-",round(roc_cnv_psa420$ci[3],3),")"),
                      paste0("fsc_score,",round(roc_fsc_psa420$auc,3),"(",round(roc_fsc_psa420$ci[1],3),
                             "-",round(roc_fsc_psa420$ci[3],3),")"),
                      paste0("fsd_score,",round(roc_fsd_psa420$auc,3),"(",round(roc_fsd_psa420$ci[1],3),
                             "-",round(roc_fsd_psa420$ci[3],3),")"))) +
  mytemp +
  theme(legend.position = c(0.65, 0.2))
ggsave("pathto/paper/fig3_2.pdf",p3,width = 4.7,height = 4.4)
```

```{r}

```

